### ISSUE TITLE
files can be downloaded without authentication!

### ISSUE THREAD

**Issue by mtsnuc** [ignacionelson/ProjectSend#132]
As this issue is closed I opened a new one: https://github.com/ignacionelson/ProjectSend/issues/69

Problem: 
If you know the filename, you can download files without any authentication. You just have to enter a valid url: e.g. http://address/upload/files/document.pdf.
This is a major security problem as you could simple brute-force a directory for files.

**Comment by lenamtl** [comment]
Hi 

Which OS are you using?

I have checked (Linux or wampserver on windows) and this is not possible,
 if your are not logged you will get this error message
You don't have permission to access url... on this server.

**Comment by mtsnuc** [comment]
Hi,

 

I’m using linux.

You can try it yourself:

 <https://drop.nucleus-server.com/upload/files/tubeConical.mov> https://drop.nucleus-server.com/upload/files/tubeConical.mov

 

 

Von: lenamtl [mailto:notifications@github.com] 
Gesendet: Dienstag, 12. Juli 2016 14:32
An: ignacionelson/ProjectSend <ProjectSend@noreply.github.com>
Cc: Marc Tschech <m.tschech@nucleus-gmbh.com>; Author <author@noreply.github.com>
Betreff: Re: [ignacionelson/ProjectSend] files can be downloaded without authentication! (#132)

 

Hi 

Which OS are you using?

I have checked (Linux or wampserver on windows) and this is not possible,
if your are not logged you will get this error message
You don't have permission to access url... on this server.

**Comment by mtsnuc** [comment]
I'm on linux:

You can try it yourself:
https://drop.nucleus-server.com/upload/files/tubeConical.mov

**Comment by lenamtl** [comment]
Which Projectsend version are you using?

**Comment by mtsnuc** [comment]
609

**Comment by lenamtl** [comment]
I cannot reproduce the problem on my servers.

Just to make sure, please check version in sys.vars.php this should show 608 (but in fack it is 609) 
https://github.com/ignacionelson/ProjectSend/issues/120

Is this a server from an hosting company or your own server?

**Comment by mtsnuc** [comment]
could it be a permissions-problem?
I had to change the upload-folder permission to 777 (which is not good anyway)

**Comment by mtsnuc** [comment]
fyi I solved the problem by modifying the apache conf.
I added:
```
Order Allow,Deny
Deny from all
```

to the upload directory.

**Comment by mriolo** [comment]
You don’t need to set the upload folder to 777 – this is the most insecure fix.
My entire ProjectSend directory tree is set to 744 and everything works beautifully.
The key is to ensure that the upload folder and it’s children are owned by the user that the web server is running under.


Matt

**Comment by lenamtl** [comment]
I'm glad you fixed it, thanks for sharing

**Comment by log4en** [comment]
the correct .htaccess in the upload/files directory must be:

`Order Deny,Allow
Deny from All
<FilesMatch "^$|(index)\.php$">
Allow from All
</FilesMatch>`

it's correct?

**Comment by mriolo** [comment]
That is what I am using.

**Comment by MGPhil** [comment]
This issue is from 2016 and I am still seeing the problem in my standard install
that files are not protected by .htaccess or do I miss something?

If a person knows a file name or makes brute-force like @mtsnuc told
every file can be downloaded as they are stored unencrypted and unprotected in the upload folder.
The standard .htaccess looks like:
```html
Options -Indexes

<FilesMatch "\.(html|htm|asp|js|ico|swp)$">
    Order Deny,Allow
    Deny from all
</FilesMatch>

<Files *.php>
    Order Deny,Allow
    Deny from all
    Allow from 127.0.0.1
</Files>

<Files index.php>
    Order Allow,Deny
    Allow from all
</Files>
``` 

But that do not Deny access to the stored files there.
Why is that .htaccess not like suggested by @log4en above in the release:

```html
Order Deny,Allow
Deny from All
<FilesMatch "^$|(index)\.php$">
Allow from All
</FilesMatch>
``` 

Thanks in advance

**Comment by ignacionelson** [comment]
Hi! I missed this fix. Sorry. Have you tried it to confirm it works on your setup?

**Comment by MGPhil** [comment]
Yes tried it right now on my setup,
with original .htaccess i can access the file if I know the name on the server or brute-force the server for files.
With changed .htaccess like that:
```html
Options -Indexes
Order Deny,Allow
Deny from All
<FilesMatch "^$|(index)\.php$">
Allow from All
</FilesMatch>
```
Browser showes Error 403 - Access not allowed, if I type the link in the browser.

Rest of the side seems to work as expected
but you all for sure know better then me what imact that .htaccess change may has.

-----------------------

Additional I checked the index.php in the upload and in the upload->files folders
which should redirect automatically to prevent access as well and they do not work for me.
I just get a blank page and no redirect.

Original code:
```html
<?php
/**
 * This file prevents direct access to the upload folder.
 * by: trainwreckjvbo on https://github.com/ignacionelson/ProjectSend/pull/500
 *
 * @package	ProjectSend
 */
ps_redirect('../../index.php');
```

If I modify it like that it works like it should and redirect to the main index.php
In upload->files folder:
```html
<?php
header("Location: ../../index.php"); 
?>
```
and in upload folder
```html
<?php
header("Location: ../index.php"); 
?>
```

Interestingly it was like my suggestion is in the initial request:
https://github.com/projectsend/projectsend/pull/500/commits/1554ca8c302cd7989f28b923059229258b6b45c4
but got changed in the process from header function to ps_redirect which I dont know why?

As I see it that 2 changes makes sense on multiple folders in the projectsend structure,
would be great if that could be in the gerneral release as it increases security by a lot in my point of view.

Just because of curiosity are all uploaded files only stored in the upload->files folder or somewere else as well?

Thanks in advance

**Comment by ignacionelson** [comment]
Thanks! The ps_redirect was a mistake, I've replaced all header('location... scripts including the ones in files that do not load PS functions.
https://github.com/projectsend/projectsend/commit/51ef3c8cf59b62528500593df832d4922c355342

I've also applied the htaccess
https://github.com/projectsend/projectsend/commit/48333efb6d190c5331af2207e3c067d15050a56b

There's also the thumbnails folder which I believe should also be protected (/uploads/thumbnails)

**Comment by MGPhil** [comment]
Hi, yes I think having the .htaccess also in the tumbnails would be important, right now I see no .htaccess there and therefore no protection.
By the way, thanks for the great tool you built here, really appreciate your work!

**Comment by MGPhil** [comment]
I tried putting .htaccess in the following folders:
upload ==> blocks thumbnails + logo on branding page (no htaccess here is not critical as subfolders can have one)
upload -> admin ==> Seams to have no negativ impact (thought that may the branding page would not show picture but works)
upload -> files ==> OK, blocks direct downloads
upload -> temp ==> Seams to have no negativ impact
upload -> tumbnails ==> Breaks the main logo on the login page + thumbnails feature

index.php to redirect direct access is ok in all mentioned folders.

Any idea how to protect tumbnails without breaking the function of them?

**Comment by MGPhil** [comment]
For fixing the branding on the main page it is possible
by adding in the .htaccess that file in the thumbnails folder has an exclusion to allow direct download.
It is only a manual fix as every branding tumbnail has a different name for every upload.
And all other tumbnails do not work then but at least it is secure that nobody can download information without access.
```html
Options -Indexes
Order Deny,Allow
Deny from All
<FilesMatch "^$|(index)\.php$">
Allow from All
</FilesMatch>
<FilesMatch "thumb_e1d57c93c8daf79140a53a2eb2db6a18_300x300.png">
Allow from All
</FilesMatch>
```

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
