### ISSUE TITLE
files uploaded "success" in web, but files show up. 

### ISSUE THREAD

**Issue by kt1024** [ignacionelson/ProjectSend#138]
after chose files and press upload, goes here:
![image](https://cloud.githubusercontent.com/assets/12657496/17134618/e6fd970e-535d-11e6-9ffe-91c64e95a16c.png)

then
![image](https://cloud.githubusercontent.com/assets/12657496/17134628/ee357a32-535d-11e6-9a44-87e6e8b55713.png)

checked in html/upload folder have only 1 file: index.php, no "uploaded" files there, also no files show up in web page "manage files"

version: r608 (yes, download r609 file, but shows 608). tested with ie/chrome/firefox.

**Comment by kt1024** [comment]
besides, ps is installed on ubuntu 14.04.

**Comment by devyljon** [comment]
Hello, 

I had this problem and its because the apache user doesn't have the right to write on the folder {PROJECTSEND_FOLDER}/upload/files/  (you have to replace {PROJECTSEND_FOLDER} by the folder who contain ProjectSend)
You can fix it by changing the owner of the folder files with:
```shell
cd  {PROJECTSEND_HOME}/upload
chmod 770 files -R
chown apache:apache files -R    
```
OR by changing the right of the folder:
```shell
$cd  {PROJECTSEND_HOME}/upload
$chmod 777 files -R
```
I hope it help.

**Comment by kt1024** [comment]
chmod 777 fix that. thanks! @devyljon
