### ISSUE TITLE
Question: FAQ & setup on IIS

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#145]
Hi,

I'm planning to make a quick FAQ for Projectsend to answer common questions.
I don't know much IIS and I'm looking some feedback about user who installed it on IIS.

Feel free to share your experience and how to solve commun issue on IIS.

Thanks

**Comment by ilackskills** [comment]
Not bother with iis

**Comment by Joohansson** [comment]
I manage to get it running on a fresh virtual windows server 2012 R2 with IIS 8.

1. Install IIS from server manager. Including features: CGI and .net 3.5 with http activation (.net needed for PHP manager later).
2. Verify that your site is running: http://localhost
3. Install PHP 5.6 and PHP manager for IIS via "Web Platform Installer 5.0". No PHP config is needed.
4. Verify PHP via http://localhost/phpinfo.php (create one if not existing). If not working, install Visual C++ Redistributable for Visual Studio 2012 Update 4 (https://www.microsoft.com/en-us/download/details.aspx?id=30679)
5. Download and extract projectsend into a new directory for example C:\inetpub\wwwroot\projectsend
6. Go to properties/security and add IUSR. Give it full control. (I think this i the correct way, I could not load any page otherwise. Another option is to connect as a different user under next step)
7. Create a virtual directory in ISS for you website. Add the projectsend folder as physical path. Connect as "application user (pass-through authentication)". There is a button "Test Settings", this gave me authorization error, but it seems to work anyway after adding IUSR in previous step.
8. Go to http://localhost/<your virtual dir>/install. Follow the steps
9. Login with your account and test upload.

**Comment by Joohansson** [comment]
I left IIS behind and moved to linux. Much much faster and no freezing uploads.
I don't think windows should be supported at all after reading this at a competitor blog:
https://owncloud.org/blog/owncloud-server-8-1-will-not-support-windows-as-server-platform-natively/

**Comment by lenamtl** [comment]
I prefer Linux.
But sometimes client don't want to change their server setup because they use IIS for other applications, so this is why it's good to have some IIS feedback with Projectsend
