### ISSUE TITLE
New user custom templates.

### ISSUE THREAD

**Issue by tsumaru720** [ignacionelson/ProjectSend#18]
New client accounts created by admin doesn't seem to be using a custom template correctly (Its just using the default one)

**Comment by ignacionelson** [comment]
How about the rest of the templates? Are they working for you?

**Comment by bwiessneth** [comment]
I can confirm what @tsumaru720 said! I created custom templates for the actions

__New client (welcome)__: Does not work
__New user (welcome)__: Works 
__Password reset__: Works

I haven't tested the other templates though. I am using version r582.

**Comment by szobi** [comment]
This bug is still there.

I substituted `EMAILS_CLIENT_BY_USER_USE_CUSTOM` for the appearances of `EMAILS_HEADER_FOOTER_CUSTOM` in line 108 of the file `includes/classes/send-email.php` (see comment of @bwiessneth above).

After that the custom email template for new a client created by user works as expected.

**Comment by lenamtl** [comment]
Could you update to the latest version and let us know if this bug is still present?

**Comment by bwiessneth** [comment]
@lenamtl Hi, thanks for the fix! I tested with the latest version and it works as intended!

**Comment by mschop** [comment]
Closing this issue, as this seems to be resolved.
