### ISSUE TITLE
Nice to have, multilangual version allow user to choose their language

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#185]
So user select and language from the login page.
This can be done using cookies or localstorage.

**Comment by ignacionelson** [comment]
Oh nice!
So there would be 3 language options for the system to choose from, and the script would need to prioritize them as:

- selected by user
- browser (if option is checked)
- system default

I think the harder part would be making the selector nice, to show the language name instead of the file name (eg: Spanish (Spain) instead of es_ES. Maybe there's a nice way of extracting it from the po file's header?

**Comment by lenamtl** [comment]
That's make sense.

**Comment by ignacionelson** [comment]
Done!
![lang](https://cloud.githubusercontent.com/assets/6926562/18608883/80dbbbe4-7ccb-11e6-883d-19c796ac357c.png)
