### ISSUE TITLE
Allow admin to edit username

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#204]
Why admin cannot edit username?

**Comment by dannyulman** [comment]
you can open php myadmin in your webhosting control panel and edit the username in the database
in the tbl_user table
I have also been able to assign the same email address to multiple accounts this way.

**Comment by ignacionelson** [comment]
The problem is that the action log stores the current username instead of the id (this is in case an account gets deleted, the register will still be visible). This also happens with the created_by column on users, groups and clients. I believe that this information should not be lost, so allowing username changes could be confusing.
