### ISSUE TITLE
Zip popup animation never end - old bug

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#205]
Hi,

One of the oldest bug is the zip feature popup animation that never end.
Is there a way to fix that or used another script?
The zip working well except the popup...
Maybe showing a bar instead anything else...

**Comment by remez** [comment]
Same here :-)

**Comment by ignacionelson** [comment]
Yes, the problem is that the request is handled through an ajax that ends up adding a hidden iframe in the popup which triggers the download. There's no way to detect when the iframe loads to close the window, so the system needs to be replaced totally.
Also, finding a new way will make it easier to add the zip function to other templates.

**Comment by remez** [comment]
Maybe can help:

https://stackoverflow.com/questions/29532788/how-to-display-a-loading-animation-while-file-is-generated-for-download

**Comment by ignacionelson** [comment]
Worked like a charm... thank you, again!!!

**Comment by remez** [comment]
Yeah! It's seems to work in Chrome with autosave and Firefox with ask for location download popup.
Great!
:-D
