### ISSUE TITLE
Bug: File Title with accent are not displayed correctly on manage-files.php

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#25]
This problem is on manage-files.php table
File Title, the accents and special characters are not well displayed.

for example : été 
will  be displayed as  and save as in the DB: ```&eacute;t&eacute;```

**Comment by lenamtl** [comment]
This also occur on client page my_files
for Title an Description

**Comment by ignacionelson** [comment]
This happened on the latest version right? How about the previous ones?

**Comment by lenamtl** [comment]
I have not tested the previous one which version exactly do you mean?
I have only use the old V 4.12 which latin was not compatible with.

**Comment by lenamtl** [comment]
The accents should not be saved like this in the database &eacute;t&eacute;
This should be saved like this été

Any french user (or other latin) have fixed the problem?

**Comment by rmasse23** [comment]
found the issue

in default/template.php

all output of title and description have htmlentities() on them. Thats explain why its ok everywhere on the website but not on view.   I modified it locally and its working flawlessly

**Comment by lenamtl** [comment]
Ok thanks 
But still, the information are not saved correctly to the database, that will be the next thing to be fix.

**Comment by rmasse23** [comment]
Well, technically, having html entities in the db data is not an issue as all browser interpret them so whatever language you save in db you will never have encoding issue (even with Catalan or non-frequent language. We often deal with that at Ticketmaster with European markets) . The issue was to force browser to print html entities with htmlentities() instead for just print db content (as it is done on other sections of the website/app .. ex: manage-files).

Cheers and your welcome!

**Comment by lenamtl** [comment]
Hi,
The problem occur also when editing a file name and description.
This will not be displayed correctly on the list for example : manage-files.php

So it's need to be done on every page where echo htmlentities appear

Check my old patch solution
https://code.google.com/p/clients-oriented-ftp/issues/detail?id=279&q=french

**Comment by lenamtl** [comment]
see #182 for possible fix
