### ISSUE TITLE
Continuity of Development

### ISSUE THREAD

**Issue by Ciscog33k** [ignacionelson/ProjectSend#361]
This is a question more for @lenamtl , will you be taking over commits and updates for ProjectSend in the near future?  @ignacionelson appears to no longer be interested, and this does need some TLC as issues are building daily and you do have heavy involvement with bug classification.

What's going on in this front?

**Comment by ignacionelson** [comment]
Oh, sad that it looks like I'm not interested :( The problem is that I work on PS when my daily job is not as busy and it's been hard this last few months. But I will not stop working on this project! If I can make some time next week I'll try to work on the urgent stuff.

**Comment by lenamtl** [comment]
Hi,
I'm using PS since the beginning, the project exist since 2010.
Per experience almost every 2 years, there is are big software updates from Ignacio.
In between big updates, users from the community are testing, asking new features, provide custom code, fixes. We are trying to help each other  ...  

This is an opensource project and people do have day job...
*You can always hire a web dev for your urgent needs.

**Comment by FloorOut** [comment]
Hi, i sent you code to fix errors in logreporting. Did you missed them? I
am nog good at git so i send you the files off-grit! I do aporeciate your
work!!!!! Floor

Op 28 feb. 2017 16:32 schreef "lenamtl" <notifications@github.com>:

**Comment by lenamtl** [comment]
Pull request or code snippet have to be tested prior to be updated to the existing package.

**Comment by FloorOut** [comment]
We did the testing and have implemented in our live-version. Do you need
more info or can i help in any way? gr. Floor

Op 1 mrt. 2017 17:09 schreef "lenamtl" <notifications@github.com>:

Pull request or code snippet have to be tested prior to be updated to the
existing package.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ignacionelson/ProjectSend/issues/361#issuecomment-283384853>,
or mute the thread

**Comment by ignacionelson** [comment]
@FloorOut can you please link me to your pull request? Thanks!
