### ISSUE TITLE
Support Amazon S3 Bucket Storage

### ISSUE THREAD

**Issue by basicmonkey** [ignacionelson/ProjectSend#466]
It would be great to have use of Amazon S3 storage as an option.

Many thanks.

**Comment by JulioC** [comment]
@ignacionelson is this on the roadmap?

**Comment by mschop** [comment]
We are planning to implement a plugin api, so that any storage provider could be added through a plugin. Currently S3 is not on our roadmap but feel free, to program a plugin as soon as the plugin api is available. Maybe plans will change in future, but currently this is not planned.
Because of that I close this issue.

@ignacionelson Please correct me, if I'm wrong on this.

**Comment by alexgilbertDG** [comment]
@mschop  Is there a plugin API so we can implement that feature ? Or is the S3 plugin already implemented ?

**Comment by mrabino1** [comment]
If I could code I would, but the implementation on espocrm is quite similar to what is needed here.. and they have s3 built it.. I personally would love to have this feature added to projectsend... 

link to s3 php code for espocrm
https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/FileStorage/Storages/AwsS3.php
