### ISSUE TITLE
When I assign a file to a client it says there are no files

### ISSUE THREAD

**Issue by allinarush** [ignacionelson/ProjectSend#530]
Everything in ProjectSend seems to work fine except the clients cannot view the files. When the client logs in it goes to page /my_files/ and there is nothing there except

1) A message that says there are no files.
2) The logo
3) Upload Files
4) Logout

When I try to mark the file as hidden (For troubleshooting Purposes) it does not save as hidden. The checkbox is still unchecked. This might help identify the problem??

Any help would be appreciated

**Comment by IB-Rahn** [comment]
Have you enabled a template? And tested it with the default one?

**Comment by mschop** [comment]
I close the issue because the issuer didn't update the issue with further details.

@allinarush If the problem still exist and you need further support, do not hesitate to reopen the issue. Please provide more details in the case, you reopen the issue. Which version are you running? Which OS, PHP-Version, etc. are you using?
