### ISSUE TITLE
Suggestion: Password generator for new accounts

### ISSUE THREAD

**Issue by crashff00** [ignacionelson/ProjectSend#67]
I added a small php password generator into the new account creation screen for users and clients. thought this might be nice for everyone else. (sorry I don't know how to actually do the code merge thing on github)

The passgenerator file is currently set to create 12 character passwords. You can change the available character and length in the passgenerator file. 

new file: includes\passgenerator.php
modified file: users-form.php, clients-form.php

[users-form.php.txt](https://github.com/ignacionelson/ProjectSend/files/44141/users-form.php.txt)
[clients-form.php.txt](https://github.com/ignacionelson/ProjectSend/files/44140/clients-form.php.txt)
[passgenerator.php.txt](https://github.com/ignacionelson/ProjectSend/files/44138/passgenerator.php.txt)

**Comment by Joohansson** [comment]
Thanks, I will try this. +1 for future implementation. Maybe generate password based on global setting for minimum password requirement. Maybe also use a better generator for higher security, read here about RandomLib:
http://stackoverflow.com/questions/6101956/generating-a-random-password-in-php/31284266#31284266

**Comment by ignacionelson** [comment]
I'm currently writing a class for generating forms and handling the validations automatically, instead of having to write everything manually (fields, types of validations, etc) like PS is using now.
One of the functions already added is the generate button for password fields (when using as CREATE pass, not USE -like the login one). Hoping to finish this this week.
I've found a javascript password generation script called Jen that seems to be secure and is the one I'm using on the tests. 
Wouldn't have done this class for a long time if it wasn't for your suggestion and code!

![generating-the-form](https://cloud.githubusercontent.com/assets/6926562/18233289/8601fe24-72b9-11e6-8f00-5d97f0f6996d.jpg)
![results](https://cloud.githubusercontent.com/assets/6926562/18233290/86208b14-72b9-11e6-828d-7768c483f3ac.jpg)

**Comment by ignacionelson** [comment]
Done! The new class is not implemented yet, but the generator is. Thanks!!!
