### ISSUE TITLE
ProjectSend still active?

### ISSUE THREAD

**Issue by VernonGrant** [ignacionelson/ProjectSend#71]
I have been using ProjectSend internally at work and it's been working amazingly well but there are a list of small bugs that needs to be fixed. I also would really like to contribute to the project but noticed that there are 9 open pull requests and the last commit was in the beginning of July. Is this project still active?

Thanks

**Comment by lenamtl** [comment]
Hi,

I beleive it is still active, but not updated often.

I'm working on a forked version, the first release will be available soon.

Feel free to post the bugs list so we can fix it. 

Thanks

**Comment by VernonGrant** [comment]
:+1: Ok Thanks

**Comment by VernonGrant** [comment]
I just reopened this issue (if I can even call it that) because I'm sure there's more people wondering about this. @lenamtl If you want me close this please do let me know : -)

Thanks

**Comment by lenamtl** [comment]
No problem.

By the way, not all pull request will be necessarily included, also every fix need to be test thoroughly.
I will take a look of your latest pull...

Most of us are working on this only part time, we have day job ;)

I have almost completed my first forked version.
I'm into a rush right now, I hope this will be ready next february/march.

Regards

**Comment by BastienDurel** [comment]
Hi.

I'm adding some features I miss for a projet at work. Is your fork public (on github or anywhere) so I can check it out and maybe spend my efforts on this new version ?

**Comment by lenamtl** [comment]
This is not completed yet, but it will be on Github in february.
I'll let you know when it will be available

**Comment by ultramizer** [comment]
Hey guys
Let me know if you have updates. I would have some very nice suggestions that would include beeing able to connect users to clients, so that you can notify some or few users when a certain client uploads new stuff. As of right now you can only specify some e-mails and everyone then get's an alert if any client uploads something. But usually we have different people handling different customers, so they would have to know when their client uploads something. Let me know if i should post this anywhere else as a suggestion! Thanks!

**Comment by alex360off** [comment]
Interesting project. I'll stay tuned and i'm waiting for some news!

**Comment by lenamtl** [comment]
Hi,
I just want to let you know that I have merge a pulled request regarding security fixes.
