### ISSUE TITLE
Multiple File Delete not logged

### ISSUE THREAD

**Issue by crashff00** [ignacionelson/ProjectSend#72]
I had 11 files that were expired, so I selected them all from the Manage Files list. When I deleted them, only the first file in the list was actually logged.

Result:
11 Files selected
11 Files Deleted.
1 Delete Action recorded.

**Comment by lenamtl** [comment]
Confirmed

**Comment by crashff00** [comment]
The files were actually a mixed set of client and user uploaded, 2 user uploads were expired status. None of them were in the first row. I have my installation set up to display 75 rows at a time.

I have not made any modifications because I'm not sure how/where to. I can dissect code and modify it somewhat when I know what to look for, but I have no skill with sql/php integration when it comes to form input, so I dont know where to even look.

**Comment by lenamtl** [comment]
You can make this fix manually as a temporary solution, this will fix bugs on delete and this should log all delete files as well.

Always made a backup of you files prior any modification

Use notepad++ to edit the file
manage-files.php 
line 527
find
$file_id = $data_file['id'];
and replace it by
$file_id = $data_file['file_id']; 
save

refresh the page and try again

**Comment by crashff00** [comment]
I fixed manage-files.php back in October with that bug fix. The missing log entries is a separate issue.

**Comment by mriolo** [comment]
The discrepancy occurs because the query run in manage-files.php on line 166 attempts to pull all files related to the current user, however when you are running as admin the files are not related to your user_id.  If there happens to be an entry in the file_associations table with an id that matches the file id of the correct file, the log will display the incorrect file data.  I was able to correct this issue by creating a conditional around building the sql query:
if ($current_level = 9) {
$sql_distinct_files = $database->query("SELECT file_id FROM tbl_files_relations WHERE file_id IN ($files_to_get)");
} else {
$sql_distinct_files = $database->query("SELECT file_id FROM tbl_files_relations WHERE clientid = ($global_id)");
}
This allows sys admins to see all files, while others can only manage the files associated with them, and correctly reads the filenames for logging.

**Comment by crashff00** [comment]
Mrolio, I don't think this is the solution I'm after. Every file uploaded to my system are associated to the admin by default. I hardcoded that association into the upload process. I did this as a fix to the bug where unassigned files couldn't be deleted. Since I'm logging in as the admin, everything is related to me.

**Comment by mriolo** [comment]
Then you can just change the query string in manage-files.php line 166 to:
$sql_distinct_files = $database->query("SELECT file_id FROM tbl_files_relations WHERE file_id IN ($files_to_get)");
and it will correctly read the filenames for later logging.  This might turn out to be the best resolution, but I used the conditional because non-admin system users can access that page, and I didn't want to create any potential for a security issue. That said, from what I can tell, the date returned from that particular query is only used for the log entries, and it is based on the files selected in the posted form data, so in theory, the user wouldn't have been able to select any files they didn't already have permission to modify or delete anyway.

**Comment by crashff00** [comment]
I will give it a spin and see what comes out.

**Comment by lenamtl** [comment]
Hi, 
If you have the time you can use my list
I have made a list of test maybe not complete one but this is a start.
https://github.com/ignacionelson/ProjectSend/issues/73

**Comment by mriolo** [comment]
I think that there will still be a logging issue even with the conditional I proposed above. In the query referenced above, the file_id field is being pulled from tbl_files_relations ... which for crashff00 should work because he said he modified his system to add an association to the sysadmin for every upload.  Without his modification however, I don't believe files appear in tbl_files_relations if they are uploaded by a system user but not assigned to any clients. Because of that, looking up the initial file data for logging purposes from that table, will potentially return incomplete query results, even applying the conditional modification I initially suggested.  I think the best solution might be to remove the lookup in tbl_files_relations altogether, and just query the data from tbl_files.

**Comment by mriolo** [comment]
To summarize, comment lines 166-171 from manage-files.php and file deletes get logged properly

**Comment by crashff00** [comment]
lenamtl, 
Here was the custom code I put in  (entry #4):
https://code.google.com/p/clients-oriented-ftp/issues/detail?id=497&q=crashff00%40gmail.com&sort=-id

**Comment by mriolo** [comment]
I think the additional association code you originally added/modified becomes unnecessary, in relation to this particular issue, if you comment the first query as I suggested.
In looking at the issue crash referenced, it looks like there was originally a two-fold issue. The file id fix on line 529(in my system) in manage_files.php is required to delete the appropriate file(s), but it doesn't correct the logging issue, unless every file that is uploaded gets assigned, and the file ids happen to coincide between the two tables.  I agree more complete testing needs to be performed.  I will try to do so as soon as I can to assist.

**Comment by crashff00** [comment]
Interestingly, since I commented the lines suggested, no delete functions are being logged now.

**Comment by mriolo** [comment]
I'm guessing maybe the line numbers changed because of previous code mods?
What should be commented is the first query against tbl_file_relations near line 166 and lines that process the result set, up to the next query.  I retested just now and my system is still logging the delete of both a single or multiple associated or unassosciated files.





Sent from my iPad
On Jan 29, 2016, at 7:19 PM, crashff00 <notifications@github.com<mailto:notifications@github.com>> wrote:


Interestingly, since I commented the lines suggested, no delete functions are being logged now.

—
Reply to this email directly or view it on GitHub<https://github.com/ignacionelson/ProjectSend/issues/72#issuecomment-177029295>.

CONFIDENTIALITY NOTICE: The information contained in this message and any attachments is legally privileged and confidential intended only for the use of the individual or entity named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this message or any attachments is strictly prohibited. If you are not the intended recipient, please reply to the sender that this message was misdirected, delete the message and any attachments and do not retain any copies. This message and any attachments may contain opinions, conclusions, and other information that do not relate to the official business of Drummond & Drummond, LLP. If so, Drummond & Drummond, LLP does not endorse them.

**Comment by crashff00** [comment]
I downloaded the 609 file today and set up a test environement. Selecting multiple files for delete is once again not working correctly. Files are selecting and deleting properly, but the wrong files are being logged.  This includes files uploaded by users and clients.
![logged](https://cloud.githubusercontent.com/assets/14809570/15945033/4785f744-2e45-11e6-8c66-def9ab178e12.png)
![selected](https://cloud.githubusercontent.com/assets/14809570/15945032/478593e4-2e45-11e6-83b9-9644ef620069.png)

**Comment by lenamtl** [comment]
In the newest version, this bug was not fixed, Ignacio switch mysql to use PDO with prepared statement, no bugs fixes or new features added.

**Comment by crashff00** [comment]
Has this been rectified with 611 yet? It's a little disheartening to go forward in version and go backwards in bug fixes.

**Comment by lenamtl** [comment]
This is fixed now let me know if you still encounter the problem.
