### ISSUE TITLE
Download Count, Not Counting

### ISSUE THREAD

**Issue by therealahm** [ignacionelson/ProjectSend#79]
Using version r582. 

Download count not working: 
— not showing on Dashboard > Statistics graph; 
— not showing in Recent Activities > Downloads; 
— is showing under Recent Activities > All Activities, though not always, and when it does only once. 

![image-2](https://cloud.githubusercontent.com/assets/17187805/12995532/1b2224f4-d0f6-11e5-91f2-cf39da4ca8bf.jpg)

![image-1](https://cloud.githubusercontent.com/assets/17187805/12995531/1b2202d0-d0f6-11e5-97fa-4540bc314590.jpg)

**Comment by lenamtl** [comment]
Hi could you clarify in which circonstance.

For example Admin/system user, download are not calculated.

Is it a public file, does the file is assign to one unique client, to a group, is it an expired files,
does the file was upload by admin or user ...
So we can point the exact problem.

**Comment by therealahm** [comment]
— Files are all public and without expiration, they are also not assigned to anyone users or groups. But you should know that by my screenshot which the files as unassigned, or "assign to:" nobody. — Downloads have all been by users with direct links or public URLs, i.e. with ID and token in the URL. — Uploads have been by many public "users"; did a test with a registered user, myself the admin, which apparently does not add to the download count. — — — Can I ask why all the stipulations about what and when to increase the download count? If anyone downloads a file, admin, public user, registered user, some registered user in a group, who cares, it should all add to the download count; and if not add to the download count, it should certainly add to the Recent Activities > All Activities list, and it doesn't.

**Comment by lenamtl** [comment]
I see, I'm not the author, I don't know what are the rules about this.

I just know that admin download are not counted.
I ask about scenario because this is the way to find out the condition is not working.

Unfortunately there is no quick solution, you will have to check the code and adapt it to your needs.

To my opinion all download should be logged as an activities, about the download count I guess this is depending of needs.

However we should know which condition is working and those that are not to make future adjustments.

PS: which PHP version are you using?

**Comment by jerob** [comment]
Same problem here :
Files are all public, not assigned to any users or groups. All the files have 0 download.

**Comment by jerob** [comment]
In the file download.php line 52, to count the public downloads, I added this code :

`$database->query('INSERT INTO tbl_downloads (file_id) VALUES ("' . (int)$_GET['id'] .'")');`

**Comment by StevieTrance** [comment]
I have added this line and it doesn't seem to work, I am using the latest version of Project Send.

**Comment by ignacionelson** [comment]
Hi Stevie!
On your code, replace `tbl_downloads` with the dynamic table name, so instead of 

`$database->query('INSERT INTO tbl_downloads (file_id) VALUES ("' . (int)$_GET['id'] .'")');`

you get

`$database->query('INSERT INTO ' . TABLE_DOWNLOADS . ' (file_id) VALUES ("' . (int)$_GET['id'] .'")');`

**Comment by StevieTrance** [comment]
...and just like magic it works! Thank you!

**Comment by ignacionelson** [comment]
No problem!
I'm actually adding this right now so it becomes part of the software.

**Comment by ignacionelson** [comment]
:D

![downloads-page](https://cloud.githubusercontent.com/assets/6926562/18575794/d4d440e2-7bb1-11e6-8919-f57287872bcf.png)

**Comment by ignacionelson** [comment]
Home graph
![home](https://cloud.githubusercontent.com/assets/6926562/18575939/f41aa45e-7bb2-11e6-9154-c2ce967acd0a.png)

**Comment by StevieTrance** [comment]
This has made my day. :) when do you think it I'll be ready?

**Comment by ignacionelson** [comment]
I'm hoping tomorrow! Only a small bug left for this milestone that I'd like to resolve, and I'm on it now.

**Comment by StevieTrance** [comment]
Great, I'll look forward to roadtesting the new feature. Have a great weekend.

**Comment by ignacionelson** [comment]
r754 with this feature is now available. Thanks for your input and support!!
