### ISSUE TITLE
Multiple Security Vulnerabilities

### ISSUE THREAD

**Issue by zorrobiwan** [ignacionelson/ProjectSend#80]
Hi,

I'm a little bit afraid when I read this page https://www.exploit-db.com/exploits/39385/

Do you consider to solve all these vulnerabilities at short term ?

You script is really useful but unusable with these vulnerabilities ...

Really thank you for your job !

**Comment by lenamtl** [comment]
I'm not the author, but I know some security bugs was fixed in the past.
I'm don't know if those are new or already fixed..
If this new ones these need to be fix ASAP and need to be test seriously.

**Comment by mhelwig** [comment]
Just had a look in the code, these security issues are still present and should urgently be fixed. Otherwise I think it's a great project so its a pity that the main dev is not aware of a secure coding style.

**Comment by zorrobiwan** [comment]
We don't have to blame someone coding and offering his job/time for free (event these errors are very common and serious ones). We could just use another software :)

I'm just asking if these vulnerabilities will be removed or not. Then I'll take my decision ...

**Comment by baldzern4** [comment]
There are two kind of issues:
- SQL injection -> correct handling / escaping of external provided data is missing
- Cookie check -> All pages are relying on the fact that they are not called directly, and the session/cookie checks are in the header.php

**Comment by baldzern4** [comment]
A quick fix for the cookie issue is to add the cookie/session check to the sys.includes.php file.
Thus all files/pages (even called directly) will checking the existence and validity of the users cookie/session.
Because the index.php is the only page which also has to be accessed by a not logged in user, you have to exclude this page from doing this check, i.e. by using an own sys.includes.php .

**Comment by mhelwig** [comment]
Sorry I didn't want to blame someone. It's a great project and I respect the work that had gone into it.
The activity has not been that high in the last month on this project, so I doubt we will get a quick solution soon. I'll have a look into the code myself and see if I can do something. The sql injections should not be too hard to handle. Of course, I'd be glad about any fix we get for these issues soon.

**Comment by lenamtl** [comment]
I would like to rewrite the code to use PDO & prepare statement, this is my plan, but at the moment I'm very busy with my day job...

**Comment by baldzern4** [comment]
@lenamtl  +1

**Comment by baldzern4** [comment]
Hi,
I think I fixed all these issues in my fork. See https://github.com/ignacionelson/ProjectSend/compare/master...baldzern4:master

If you like, I can create a pull request and you can cherry pick the changes.

## Changes

**SQL injection:** 
fixed by adding `mysql_real_escape_string(...)` to the variables.

**Authentication Bypass /  Insecure Direct Object References**
fixed by adding 
```
if (! check_for_session() ) {
   die();
}
```
to sys.includes.php while adding a new one (without this check) for the index.php page.

:warning: I know this is ugly but my PHP skills are not that good and I needed a quick solution because this security issue allows an attacker to add an Admin account, download all content and then remove all other users. :scream: 

**Arbitrary File Download**
fixed by only allowing alphanumeric chars,  dots, hyphens, underscore and spaces

Br,

**Comment by mhelwig** [comment]
@baldzern4 Thanks!

I spent the last hours doing the same thing. Maybe we should compare and merge.

A rewrite with better database handling would be great but that is going to take some time. For people who already use this code in production it may be too late.

I'm going to test it a little bit more but I do not have the time to do that today.

If you want to have a look at my version, go here: https://github.com/mhelwig/ProjectSend

Good that this project receives some attention : )

**Comment by baldzern4** [comment]
@mhelwig  Your changes looking good (and better) than mine. 

Greetings from Hamburg :smile:

**Comment by zorrobiwan** [comment]
Glad to see motivated people reacting to my post and ready to help to author ! ;-)

Greetings from Mont-Saint-Guibert (Belgium)

**Comment by mhelwig** [comment]
@baldzern4 Thanks! Greetings from (nearly) Cologne : )
Your way of handling the general being-logged-in requirement for all but index.php is definitely the better approach than checking the individual files. Have you tested if it breaks the app somewhere? The only thing I don't like about it is that we need two versions of the sys.includes.php, we should solve that differently in the long run.
The path-traversal is probably better handeled via basepath. For the SQL-Injections there are not much possibilities without rewriting the whole database adapter.

**Comment by baldzern4** [comment]
@mhelwig I have all my fixes already running in our production environment.  Up to now everything looks fine.

I had the same concerns regarding the two different sys.includes.php files. I tried to check if the code is running in the index.php context so we only have to maintain one file, but I didn't succeeded (I am really no PHP expert) and I had only little time to secure our service.

**Comment by mhelwig** [comment]
There has been another possible injection vulnerability in the myfiles/index.php that hasn't been noticed so far. I also checked that in.
However, after having another look at the code, I fear that there is a lot more hidden in it so I would not recommend to use ProjectSend at this time. Even with our added fixes (which need more testing) there is too much going on that still needs a closer look.

**Comment by lenamtl** [comment]
Thanks a lot I have contacted the author just to see how we will manage this.

I will start testing you pull in a day or two.
If other user can do the test it too, we can get a more secure solution quickly.

Thanks, every effort is important and it will give a good result at the end.

**Comment by lenamtl** [comment]
Hi I have merge the pull request, I made a few tests but certainly need to do more test, please let us know if you encounter any issue with the updates.

**Comment by mhelwig** [comment]
Thanks! We have this code already in use in a small production environment and there haven't been any issues so far. More exhaustive tests would be nice, though.

**Comment by lenamtl** [comment]
Someone report some security issue are they the same?
See#88

**Comment by lenamtl** [comment]
Hi, anyone have a suggestion to replace thimthumbs that have security issue
#31

**Comment by baldzern4** [comment]
Hi,
as far as I know the one security vulnerability allows anyone to upload any php file into the Timthumb cache directory and execute it to compromise the site (1), the other will execute OS commands fetched from a remote URL (2).

see:
(1) http://www.agentwp.com/how-to-fix-the-security-issue-in-timthumb
(2) https://www.exploit-db.com/exploits/33851/

If I look at the ProjectSend settings, then we should be safe because both important variables are set to false:
```
define( 'ALLOW_EXTERNAL', false );
define ('WEBSHOT_ENABLED', false); 
```

In addition we have set the file cache directory to an outside tmp folder in our version: 
`define ('FILE_CACHE_DIRECTORY', '/tmp/cache');  ` 

So we should be safe for now.

Br,
Jörg

**Comment by lenamtl** [comment]
Ok thanks a lot for the info

**Comment by lenamtl** [comment]
Hi, just to let you know the new update is now using PDO prepare statement
