### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by ppasserini** [ignacionelson/ProjectSend#88]
Hi,
just in case, I'm sure somebody else already reported:

http://www.siph0n.pw/exploits.php?id=3809

I just tested the last one and it still works.

**Comment by mhelwig** [comment]
These are old ones that have been known before and apply to r561 (as you can see from the post requests and the date of publishing). I didn't test them and I assumed they were fixed, but if the last one still works, that's definitely bad news.
Seems the fileupload has already been discussed here: https://github.com/ignacionelson/ProjectSend/issues/61 and should be fixed now. 
Can somebody confirm if it is fixed in the master branch?
We probably need to check if the other ones are still relevant.

**Comment by ppasserini** [comment]
I hope it's my mistake. I tested with r582 not with the master branch. I'll try to doble check it.

**Comment by lenamtl** [comment]
Yes the pull request #61 have been merge already to the package

**Comment by lenamtl** [comment]
make sure you download the latest package from github.
The version number doesn't match, the old version number still appear.
This need to be update

**Comment by ppasserini** [comment]
Yes. I just finish to repeat the same (with the package from github) and looks like it's working correctly.
Also Apache log report 432 (Request is incomplete) instead of 574:

"POST /psend/process-upload.php?name=/temp/test.py HTTP/1.1" 302 432 "-" "python-requests/2.4.3 CPython/2.7.9 Linux/3.16.0-4-amd64"

Thanks

**Comment by lenamtl** [comment]
@ppasserini Sorry about my ignorance but what 574 correspond to ?

**Comment by ppasserini** [comment]
It's not a question of ignorance, I don't know exactly the meaning. I found only:
500-599  Errors have occurred in the server itself.
...but a different code means also a different behaviour  :-)

**Comment by NumberFourAG** [comment]
Hi, 
the issues should be fixed with #80 because they target the same weakness. 
The Upload issue was already discovered and fixed in  #61.

**Comment by baldzern4** [comment]
Hi, 
the issues should be fixed with #80 because they target the same weakness. 
The Upload issue was already discovered and fixed in #61.

**Comment by lenamtl** [comment]
Ok then I close this
